#!/bin/bash

MAIN_PKGS() {
sudo xbps-install -Syu -u xbps && sudo xbps-install -Syu
sudo xbps-install -Syu xfce4 xfce4-whiskermenu-plugin alsa-pipewire pipewire libspa-bluetooth bluez blueman xfce4-pulseaudio-plugin pavucontrol papirus-icon-theme arc-theme evince torbrowser-launcher gnome-calculator scrot qbittorrent mpv firefox chromium torbrowser-launcher github-cli neofetch ntfs-3g xorg-minimal xorg-fonts network-manager-applet telegram-desktop gvfs-mtp gvfs file-roller os-prober vim git xf86-input-libinput 
}



START_SERVICES(){
sudo mkdir -p /etc/alsa/conf.d
sudo ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
sudo ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d

sudo ln -s /etc/sv/dbus /var/service
sudo ln -s /etc/sv/bluetoothd /var/service
sudo ln -s /etc/sv/polkitd /var/service
sudo ln -s /etc/sv/rtkit /var/service
sudo ln -s /etc/sv/elogind /var/service
sudo echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

sudo echo '
Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lmr"
EndSection ' >> /etc/X11/xorg.conf.d/30-touchpad.conf
}



CNWR_CY() {
cp -r .config .xinitrc .zshrc .fonts /$HOME/ 
fc-cache -fv

}







REBOOT_CASE() { 
clear && /bin/echo -e '\n\n' "\e[1;32mREBOOTING NOW......\e[0m"
sleep 1
clear && /bin/echo -e '\n\n' "\e[1;31mEXITING......\e[0m" 
sudo reboot
}


#runfunctions

MAIN_PKGS 
START_SERVICES
CNWR_CY
REBOOT_CASE
